### ISSUE TITLE
Problems with installing haskell and copilot

### ISSUE THREAD

**Issue by matheeusper** [simondlevy/LambdaFlight#14]
![image](https://github.com/simondlevy/LambdaFlight/assets/126926145/1945f3e5-ddd3-4fd9-89c3-4daf444866f0)
I'm having problems with copilot, I installed GHC through Windos PowerShell and after that I used cabal install copilot, and even following the recommendations in the error output I'm having the following error in the image. Would there be more complete documentation on how to correctly install and configure Haskell and copilot?

I've never used Haskell and I'm not familiar with how to install and use it.

**Comment by simondlevy** [comment]
You also need to install copilot-c99

**Comment by matheeusper** [comment]
![image](https://github.com/simondlevy/LambdaFlight/assets/126926145/8bd2b26d-c613-46d8-ab3c-cdd06f084501)
now I have the following errors

**Comment by matheeusper** [comment]
did not work
